// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.3
// source: proto/foo.proto

package main

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SystemUsage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Foo int64  `protobuf:"varint,1,opt,name=foo,proto3" json:"foo,omitempty"`
	Bar string `protobuf:"bytes,2,opt,name=bar,proto3" json:"bar,omitempty"`
}

func (x *SystemUsage) Reset() {
	*x = SystemUsage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_foo_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SystemUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemUsage) ProtoMessage() {}

func (x *SystemUsage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_foo_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemUsage.ProtoReflect.Descriptor instead.
func (*SystemUsage) Descriptor() ([]byte, []int) {
	return file_proto_foo_proto_rawDescGZIP(), []int{0}
}

func (x *SystemUsage) GetFoo() int64 {
	if x != nil {
		return x.Foo
	}
	return 0
}

func (x *SystemUsage) GetBar() string {
	if x != nil {
		return x.Bar
	}
	return ""
}

var file_proto_foo_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         50002,
		Name:          "foo.v1.is_timestamp_option",
		Tag:           "varint,50002,opt,name=is_timestamp_option",
		Filename:      "proto/foo.proto",
	},
}

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional bool is_timestamp_option = 50002;
	E_IsTimestampOption = &file_proto_foo_proto_extTypes[0]
)

var File_proto_foo_proto protoreflect.FileDescriptor

var file_proto_foo_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x66, 0x6f, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x06, 0x66, 0x6f, 0x6f, 0x2e, 0x76, 0x31, 0x1a, 0x20, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x65, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x37, 0x0a, 0x0b, 0x53,
	0x79, 0x73, 0x74, 0x65, 0x6d, 0x55, 0x73, 0x61, 0x67, 0x65, 0x12, 0x16, 0x0a, 0x03, 0x66, 0x6f,
	0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x42, 0x04, 0x90, 0xb5, 0x18, 0x01, 0x52, 0x03, 0x66,
	0x6f, 0x6f, 0x12, 0x10, 0x0a, 0x03, 0x62, 0x61, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x62, 0x61, 0x72, 0x3a, 0x4f, 0x0a, 0x13, 0x69, 0x73, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x5f, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1d, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x46, 0x69,
	0x65, 0x6c, 0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0xd2, 0x86, 0x03, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x11, 0x69, 0x73, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x4f,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_foo_proto_rawDescOnce sync.Once
	file_proto_foo_proto_rawDescData = file_proto_foo_proto_rawDesc
)

func file_proto_foo_proto_rawDescGZIP() []byte {
	file_proto_foo_proto_rawDescOnce.Do(func() {
		file_proto_foo_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_foo_proto_rawDescData)
	})
	return file_proto_foo_proto_rawDescData
}

var file_proto_foo_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_foo_proto_goTypes = []interface{}{
	(*SystemUsage)(nil),               // 0: foo.v1.SystemUsage
	(*descriptorpb.FieldOptions)(nil), // 1: google.protobuf.FieldOptions
}
var file_proto_foo_proto_depIdxs = []int32{
	1, // 0: foo.v1.is_timestamp_option:extendee -> google.protobuf.FieldOptions
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	0, // [0:1] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_foo_proto_init() }
func file_proto_foo_proto_init() {
	if File_proto_foo_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_foo_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SystemUsage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_foo_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_proto_foo_proto_goTypes,
		DependencyIndexes: file_proto_foo_proto_depIdxs,
		MessageInfos:      file_proto_foo_proto_msgTypes,
		ExtensionInfos:    file_proto_foo_proto_extTypes,
	}.Build()
	File_proto_foo_proto = out.File
	file_proto_foo_proto_rawDesc = nil
	file_proto_foo_proto_goTypes = nil
	file_proto_foo_proto_depIdxs = nil
}
